# Generated by Django 4.2.7 on 2024-01-26 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('VIP', 'VIP'), ('Regular', 'Regular')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_ticket', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event')),
            ],
            options={
                'unique_together': {('event', 'ticket_type')},
            },
        ),
    ]
