# Generated by Django 4.2.7 on 2024-02-15 12:49
from datetime import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='refund_deadline',
            field=models.DateTimeField(datetime(2024, 2, 16, 12, 0, 0)),
            preserve_default=False,
        ),
    ]
