# Generated by Django 4.2.7 on 2024-02-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_purchase_refund_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='refund_deadline',
            field=models.DateTimeField(),
        ),
    ]
