# Generated by Django 4.2.7 on 2024-01-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventappuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/anon_profile_image.png', null=True, upload_to=''),
        ),
    ]
