# Generated by Django 4.2.7 on 2024-01-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_auth', '0004_alter_eventappuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventappuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/static/images/anon_profile_image.png', null=True, upload_to='profile_images/'),
        ),
    ]
