# Generated by Django 4.2.7 on 2024-01-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_auth', '0005_alter_eventappuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventappuser',
            name='profile_picture',
            field=models.ImageField(default='/static/images/anon_profile_image.png', upload_to='profile_images/'),
        ),
    ]
